version: '3'
services:
  app:
    image: bill-services-app
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./Wallet_OZARZE8P1JOTCP4N:/Wallet_OZARZE8P1JOTCP4N

networks:
  default:
    driver: bridge  